export const albums = {
  data: () => ({
    album: [
      {
        key: 14,
        img: 'fjqmfflwm_album.jpg',
        name: 'UNFORGETTABLE',
        date: '2020.09.01',
        tracklist: [
          { song: '1. Unforgettable' },
          { song: '2. Obliviate' },
          { song: '3. 자각몽' },
          { song: '4. 절대, 비밀' },
          { song: '5. 이야기꽃' },
          { song: '6. 걱정 인형' },
        ],
      },
      {
        key: 13,
        img: 'lovelyz_6th.jpg',
        name: 'Once upon a time',
        date: '2019.05.20',
        tracklist: [
          { song: '1. Once upon a time' },
          { song: '2. 그 시절 우리가 사랑했던 우리(Beautiful Days)' },
          { song: '3. Close To You' },
          { song: '4. Sweet Luv' },
          { song: '5. Secret Story' },
          { song: '6. LOVE GAME' },
        ],
      },
      {
        key: 12,
        img: 'thumb_babysoul.jpg',
        name: '조각달',
        date: '2019.04.23',
        tracklist: [{ song: '1. 조각달' }],
      },
      {
        key: 11,
        img: 'lovelyz_5th.jpg',
        name: 'LOVELYZ 5th MINI ALBUM [SANCTUARY]',
        date: '2018.11.26',
        tracklist: [
          { song: '1. Never Ending' },
          { song: '2. 찾아가세요' },
          { song: '3. Like U' },
          { song: '4. Rewind' },
          { song: '5. Rain' },
          { song: '6. 백일몽' },
          { song: '7. 꽃점' },
        ],
      },
      {
        key: 10,
        img: 'lovelyz_mom.jpg',
        name: 'LOVELYZ Instrumental Album [MUSE ON MUSIC]',
        date: '2018.09.10',
        tracklist1: [
          { song: '1. Destiny (나의 지구) ' },
          { song: '2. 비밀여행' },
          { song: '3. 놀이공원' },
          { song: '4. 이별 Chapter 1' },
          { song: '5. 퐁당' },
          { song: '6. WoW!' },
          { song: '7. 숨바꼭질' },
          { song: '8. Aya' },
          { song: '9. 그냥' },
          { song: '10. 졸린 꿈' },
          { song: '11. 비밀정원 ' },
        ],
        tracklist2: [
          { song: '1. 안녕 (Hi~)' },
          { song: '2. Candy Jelly Love' },
          { song: '3. Ah-Choo' },
          { song: '4. Hug Me' },
          { song: '5. 그대에게' },
          { song: '6. 1cm' },
          { song: '7. Cameo' },
          { song: '8. Emotion' },
          { song: '9. 지금, 우리' },
          { song: '10. 종소리' },
          { song: '11. 삼각형' },
        ],
        tracklist3: [
          { song: '1. 어제처럼 굿나잇' },
          { song: '2. 남보다 못한 사이 Feat. 휘성 (Babysoul Solo)' },
          { song: '3. 너만없다 (JIN Solo)' },
          { song: '4. 작별하나' },
          { song: '5. Circle' },
          { song: '6. 책갈피' },
          { song: '7. 새벽별 (Babysolu & Kei & JIN)' },
          { song: '8. 첫눈' },
          { song: '9. Night and Day' },
          { song: '10. FALLIN’' },
          { song: '11. 인형' },
        ],
      },
      {
        key: 9,
        img: 'lovelyz_4album.jpg',
        name: 'LOVELYZ 4RD MINI ALBUM [治癒]',
        date: '2018.04.23',
        tracklist: [
          { song: '1. 治癒(치유)' },
          { song: '2. 그날의 너' },
          { song: '3. 미묘미묘해' },
          { song: '4. Temptation' },
          { song: '5. 수채화' },
          { song: '6. SHINING★STAR' },
        ],
      },
      {
        key: 8,
        img: 'thum_fallin.jpg',
        name: 'LOVELYZ 3RD MINI ALBUM [FALL IN LOVELYZ]',
        date: '2017.11.14',
        tracklist: [
          { song: '1. Spotlight' },
          { song: '2. 종소리' },
          { song: '3. 삼각형' },
          { song: '4. 그냥' },
          { song: '5. FALLIN’' },
          { song: '6. 비밀정원' },
          { song: '7. 졸린 꿈' },
        ],
      },
      {
        key: 7,
        img: 'album_nowus.jpg',
        name: 'Lovelyz 2nd Album Repackage [지금, 우리]',
        date: '2017.05.02',
        tracklist: [
          { song: '1. R U Ready?' },
          { song: '2. WoW!' },
          { song: '3. 지금, 우리 [TITLE]' },
          { song: '4. Aya' },
          { song: '5. Cameo' },
          { song: '6. Emotion' },
          { song: '7. 새벽별 (Babysoul & Kei & JIN)' },
          { song: '8. 첫눈' },
          { song: '9. 똑똑' },
          { song: '10. The (Lee Mi-Joo & Ryu Su-Jeong & Jeong Ye-In)' },
          { song: '11. Night and Day' },
          { song: '12. 숨바꼭질' },
          { song: '13. 나의 연인 (Yoo Ji-Ae & Seo Ji-Soo)' },
        ],
      },
      {
        key: 6,
        img: 'album_ruready.jpg',
        name: 'Lovelyz 2nd Album [R U Ready?]',
        date: '2017.02.26',
        tracklist: [
          { song: '1. R U Ready?' },
          { song: '2. WoW!' },
          { song: '3. Cameo' },
          { song: '4. Emotion' },
          { song: '5. 새벽별 (Babysoul & Kei & JIN)' },
          { song: '6. 첫눈' },
          { song: '7. 똑똑' },
          { song: '8. The (Lee Mi-Joo & Ryu Su-Jeong & Jeong Ye-In)' },
          { song: '9. Night and Day' },
          { song: '10. 숨바꼭질' },
          { song: '11. 나의 연인 (Yoo Ji-Ae & Seo Ji-Soo)' },
        ],
      },
      {
        key: 5,
        img: 'album_anewtrilogy.jpg',
        name: 'A New Trilogy',
        date: '2016.04.25',
        tracklist: [
          { song: '1. Moonrise' },
          { song: '2. Destiny (나의 지구)' },
          { song: '3. 퐁당' },
          { song: '4. 책갈피' },
          { song: '5. 1cm' },
          { song: '6. 마음 (*취급주의)' },
          { song: '7. 인형' },
        ],
      },
      {
        key: 4,
        img: 'album_lovelinus.jpg',
        name: 'Lovelinus',
        date: '2015.12.07',
        tracklist: [
          { song: '1. 그대에게' },
          { song: '2. Circle' },
          { song: '3. Bebe' },
        ],
      },
      {
        key: 3,
        img: 'album_lovelyz8.jpg',
        name: 'Lovelyz8',
        date: '2015.10.01',
        tracklist: [
          { song: '1. Welcome To The Loveylz8' },
          { song: '2. Ah-choo' },
          { song: '3. 작별하나' },
          { song: '4. Hug Me' },
          { song: '5. 예쁜 여자가 되는 법' },
          { song: '6. 새콤달콤' },
          { song: '7. 라푼젤' },
        ],
      },
      {
        key: 2,
        img: 'album_hi.jpg',
        name: 'Hi~',
        date: '2015.03.03',
        tracklist: [
          { song: '1. Introducing the Candy' },
          { song: '2. Candy Jelly Love' },
          { song: '3. 안녕(Hi~)' },
          { song: '4. 놀이공원' },
          { song: '5. 어제처럼 굿나잇' },
          { song: '6. 이별 Chapter 1' },
          { song: '7. 비밀여행' },
          { song: '8. 남보다 못한 사이 (feat. 휘성) (Babysoul Solo)' },
          {
            song:
              '9. 그녀는 바람둥이야 (feat. 동우 Of 인피니트) (Babysoul & Kei)',
          },
          { song: '10. Delight (Yoo Ji-Ae Solo)' },
          { song: '11. 너만 없다 (JIN Solo)' },
        ],
      },
      {
        key: 1,
        img: 'album_girlsinvasion.jpg',
        name: 'Girls` Invasion',
        date: '2014.11.17',
        tracklist: [
          { song: '1. Introducing the Candy' },
          { song: '2. Candy Jelly Love' },
          { song: '3. 어제처럼 굿나잇' },
          { song: '4. 이별 Chapter 1' },
          { song: '5. 비밀여행' },
          { song: '6. 남보다 못한 사이 (feat. 휘성) (Babysoul Solo)' },
          {
            song:
              '7. 그녀는 바람둥이야 (feat. 동우 Of 인피니트) (Babysoul & Kei)',
          },
          { song: '8. Delight (Yoo Ji-Ae Solo)' },
          { song: '9. 너만 없다 (JIN Solo)' },
        ],
      },
    ],
  }),
};
